name: Deploy NestJS to aaPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Aplikasi
        run: npm run build 

      - name: Coba SSH Manual
        run: |
          echo "${{ secrets.AAPANEL_SSH_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo sukses login"

      - name: Copy files to aaPanel via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AAPANEL_SSH_KEY }}
          port: 22
          source: "dist/*,package.json,package-lock.json"
          target: "/www/wwwroot/nestjs-app"

      - name: Install Node.js 20 dan PM2 di server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AAPANEL_SSH_KEY }}
          port: 22
          script: |
            source ~/.bashrc

            # Cek apakah NVM tersedia
            if [ -d "$HOME/.nvm" ]; then
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            fi

            # Install NVM jika belum ada
            if ! command -v nvm &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            fi

            # Install Node.js 20 jika belum ada
            nvm install 20
            nvm alias default 20
            nvm use 20

            # Cek dan install PM2 jika belum ada
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

      - name: Buat .env di server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AAPANEL_SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/nestjs-app
            echo -e "${{ secrets.ENV_VARS }}" > .env
            cat .env  # Debugging, hapus jika sudah yakin aman

      - name: Restart PM2 dengan Node.js 20
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AAPANEL_SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/nestjs-app

            # Pastikan NVM dan Node.js 20 digunakan
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20

            # Install dependensi produksi
            npm install --production --omit=dev --legacy-peer-deps

            # Restart PM2 menggunakan Node.js 20
            pm2 delete nestjs-app || true
            pm2 start dist/main.js --name nestjs-app --node-args="--max-old-space-size=512"
            pm2 save
