name: Deploy NestJS to aaPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Aplikasi
        run: npm run build 

      - name: Coba SSH Manual
        run: |
          echo "${{ secrets.AAPANEL_SSH_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo sukses login"

      - name: Copy files to aaPanel via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AAPANEL_SSH_KEY }}
          port: 22
          source: "dist/*,package.json,package-lock.json"
          target: "/www/wwwroot/nestjs-app"

      - name: Install PM2 dan Node.js di server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AAPANEL_SSH_KEY }}
          port: 22
          script: |
            source ~/.bashrc
      
            # Cek apakah Node.js sudah terinstall, jika belum install
            if ! command -v node &> /dev/null; then
              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt install -y nodejs
            fi
      
            # Cek apakah PM2 sudah terinstall, jika belum install
            if ! command -v pm2 &> /dev/null; then
              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S npm install -g pm2
            fi



      - name: Buat .env di server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AAPANEL_SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/nestjs-app
            echo -e "${{ secrets.ENV_VARS }}" > .env
            cat .env  # Debugging, hapus jika sudah yakin aman

      - name: Restart PM2 di server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AAPANEL_SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/nestjs-app
            npm install --production --omit=dev --legacy-peer-deps
            pm2 restart nestjs-app || pm2 start dist/main.js --name nestjs-app
